stages:
  data_ingestion:
    cmd: python src/data/data_ingestion.py
    deps:
      - src/data/data_ingestion.py
      - data/raw/Reddit_Data.csv
    params:
      - data_ingestion
    outs:
      # We output to 'processed' now, not 'raw'
      - data/processed/train.csv
      - data/processed/test.csv

  data_preprocessing:
    cmd: python src/data/data_preprocessing.py
    deps:
      - src/data/data_preprocessing.py
      # The input here comes from the output of data_ingestion
      - data/processed/train.csv
      - data/processed/test.csv
    params:
      - preprocessing
    outs:
      # These are the cleaned files ready for vectorization
      - data/processed/train_clean.csv
      - data/processed/test_clean.csv

  
  